load("@rules_python//python:defs.bzl", "py_import")

package(default_visibility = ["//visibility:public"])

py_library(
    name="compute",
    srcs=[
        "__init__.py",
        "operators.py"
    ]
)
