#
# Configuration for this target
#

# Unique name for the workspace
workspace(name="calculator")

# Add support for Python
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.5.0/rules_python-0.5.0.tar.gz",
    sha256 = "cd6730ed53a002c56ce4e2f396ba3b3be262fd7cb68339f0377a45e8227fe332",
)

# Add the ability to install pip dependencies
load("@rules_python//python:pip.bzl", "pip_install")

# Install the dependencies specified in ./src/requirements.txt
pip_install(
   name = "calculator_requirements",
   requirements = "//src:requirements.txt",
)

# Declares the label and directory of a local but external project
# to be referenced by this one in BUILD files
local_repository(
    name = "library",
    path = "/workspace/lib",
)

# Install the pip packages from the dependency projects
pip_install(
   name = "compute_requirements",
   requirements = "@library//compute:requirements.txt",
)
