workspace(name="lib")

# The declarations below are not needed for building or running the libraries. They
# are needed for unit tests, only. The WORKSPACE files for the projects using these
# libraries contain the needed configurations to build and run.

# Python support
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.5.0/rules_python-0.5.0.tar.gz",
    sha256 = "cd6730ed53a002c56ce4e2f396ba3b3be262fd7cb68339f0377a45e8227fe332",
)

# pip dependencies
load("@rules_python//python:pip.bzl", "pip_install")

# Install pip packages
pip_install(
   name = "compute_requirements",
   requirements = "//compute:requirements.txt",
)

pip_install(
   name = "utils_requirements",
   requirements = "//utils:requirements.txt",
)
