load("@rules_python//python:defs.bzl", "py_import")

package(default_visibility = ["//visibility:public"])

py_library(
    name="utils",
    srcs=[
        "__init__.py",
        "string_utils.py"
    ]
)
